name = "satori-workers"
main = "src/index.tsx"
compatibility_date = "2022-10-11"
compatibility_flags = ["streams_enable_constructors"]
rules = [
  { type = "Data", globs = ["**/*.ttf", "**/*.otf"], fallthrough = true },
]
